### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rockers007** [jvandemo/angular2-todo-app#2]
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  E:/nodejs/test1/angular2-todo-app/tmp/broccoli_type_script_compiler-input_base
_path-mGvgaYmK.tmp/0/src/app/todo.service.ts (39, 12): Property 'assign' does no
t exist on type 'ObjectConstructor'.
  E:/nodejs/test1/angular2-todo-app/tmp/broccoli_type_script_compiler-input_base
_path-mGvgaYmK.tmp/0/src/app/todo.ts (8, 12): Property 'assign' does not exist o
n type 'ObjectConstructor'.
  E:/nodejs/test1/angular2-todo-app/tmp/broccoli_type_script_compiler-input_base
_path-mGvgaYmK.tmp/0/src/typings.d.ts (5, 1): File 'E:/nodejs/test1/angular2-tod
o-app/tmp/broccoli_type_script_compiler-input_base_path-mGvgaYmK.tmp/0/typings/i
ndex.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (E:\nodejs\test1\angular2-
todo-app\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (E:\nodejs\test1\angular2-todo-app\node_
modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at E:\nodejs\test1\angular2-todo-app\node_modules\angular-cli\node_modules\b
roccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (E:\nodejs\test1\angular2-todo-app\node_modu
les\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\nodejs\test1\angular2-todo-app\nod
e_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (E:\nodejs\test1\angular2-todo-app\node_modul
es\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (E:\nodejs\test1\angular2-todo-app\node_modules\angu
lar-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (E:\nodejs\test1\angular2-todo-app\node
_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor](E:nodejstest
1angular2-todo-appnode_modulesangular-clinode_modulesbroccoli-caching-write
rindex.js:21:10)
    at BroccoliTypeScriptCompiler (E:\nodejs\test1\angular2-todo-app\node_module
s\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (E:\nodejs\test1\angular2-todo-app\node_modules\an
gular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree (E:\nodejs\test1\angular2-todo-app\node_modules\an
gular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App (E:\nodejs\test1\angular2-todo-app\node_modules\angular-c
li\lib\broccoli\angular2-app.js:53:23)
    at module.exports (E:\nodejs\test1\angular2-todo-app\angular-cli-build.js:10
:10)
    at Class.setupBroccoliBuilder (E:\nodejs\test1\angular2-todo-app\node_module
s\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.init (E:\nodejs\test1\angular2-todo-app\node_modules\angular-cli\no
de_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (E:\nodejs\test1\angular2-todo-app\node_modules\angular-cli\nod
e_modules\core-object\core-object.js:18:12)
    at Class.run (E:\nodejs\test1\angular2-todo-app\node_modules\angular-cli\nod
e_modules\angular-cli\lib\tasks\serve.js:15:19)
    at E:\nodejs\test1\angular2-todo-app\node_modules\angular-cli\node_modules\a
ngular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (E:\nodejs\test1\angular2-todo-app\node_modu
les\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\nodejs\test1\angular2-todo-app\nod
e_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (E:\nodejs\test1\angular2-todo-app\node_modul
es\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (E:\nodejs\test1\angular2-todo-app\node_modules\angu
lar-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by brunocasarotti** [comment]
Same issue here, could you find a fix for that?

**Comment by jvandemo** [comment]
This repository is no longer valid. The latest version is available for download right here:
https://github.com/sitepoint-editors/angular-todo-app

Thanks in advance!
